mongo:
  host: 127.0.0.1
  port: 27017
  database: scheduler
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

scheduler:
  groupSplitNumber: 5

app:
  name: job-scheduelr
  error-log:
      collection: log_exception
      expireDay: 30
